exp_name: ABCD_multitask
seed: [12]
backbone: ResNet50
lambdas: [1, 20]
policy_model: task-specific


paths:
  log_dir: /home/ubuntu/3DCNN/AdaShare/experiments/logs/
  result_dir: /home/ubuntu/3DCNN/AdaShare/experiments/results
  checkpoint_dir: /home/ubuntu/3DCNN/AdaShare/experiments/checkpoints

dataload:
  dataset: ABCD
  img_dataroot_train: /home/ubuntu/HEEHWAN/preprocessed_masked/
  img_dataroot_val: /home/ubuntu/HEEHWAN/preprocessed_masked/
  label_dataroot: /home/ubuntu/HEEHWAN/ABCD_phenotype_total.csv

task:
  cat_target:
  num_target:
  targets:
  tasks_num_class:

data_split:
  warmup_size:
  train_batch_size:
  val_batch_size:

data_augmentation:
  resize:

policy: True
init_neg_logits:
is_sparse: True
is_sharing: True
skip_layer: 0
is_curriculum: True
curriculum_speed: 3
fix_BN: False
diff_sparsity_weights: True
retrain_from_pl: False

train:
  total_iters: 20000
  warm_up_iters: 4000
  lr: 0.001
  policy_lr: 0.01
  backbone_lr: 0.001
  weight_decay:
  reg_w: 0.05
  reg_w_hamming: 0.05
  print_freq: 100
  val_freq: 400
  decay_lr_freq: 4000
  decay_lr_rate: 0.5
  decay_temp_freq: 100
  init_temp: 5
  decay_temp: 0.965
  resume: False
  retrain_resume: False
  policy_iter: best
  which_iter: warmup
  init_method: equal
  hard_sampling: False

test:
  which_iter: best
